# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [64]:
import pandas as pd
import numpy as np

In [65]:
from numpy.random import randn
np.random.seed(101)

In [66]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [67]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [68]:
df1 = pd.DataFrame(np.identity(5), index=['A', 'B', 'C', 'D', 'E'], columns=['V','W', 'X', 'Y', 'Z'])
df1

     V    W    X    Y    Z
A  1.0  0.0  0.0  0.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0
E  0.0  0.0  0.0  0.0  1.0

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [69]:
df1[['W','X']]

     W    X
A  0.0  0.0
B  1.0  0.0
C  0.0  1.0
D  0.0  0.0
E  0.0  0.0

In [70]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [71]:
# Pass a list of column names
df[['W','Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [72]:
# SQL Syntax (NOT RECOMMENDED!)
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

DataFrame Columns are just Series

In [73]:
type(df1['W'])

pandas.Series

In [74]:
type(df['W'])

pandas.Series

**Creating a new column:**

In [77]:
df['new'] = df['W'] + df['Y']

In [80]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [90]:
df1

     V    W    X    Y    Z  sum
A  1.0  0.0  0.0  0.0  0.0  1.0
B  0.0  1.0  0.0  0.0  0.0  1.0
C  0.0  0.0  1.0  0.0  0.0  1.0
D  0.0  0.0  0.0  1.0  0.0  1.0

In [89]:
df1['sum'] = df1['V'] + df1['W'] + df1['X'] + df1['Y'] + df1['Z']
df1

     V    W    X    Y    Z  sum
A  1.0  0.0  0.0  0.0  0.0  1.0
B  0.0  1.0  0.0  0.0  0.0  1.0
C  0.0  0.0  1.0  0.0  0.0  1.0
D  0.0  0.0  0.0  1.0  0.0  1.0

In [81]:
df1.drop('sum', axis=1, inplace=True)
df1

     V    W    X    Y    Z
A  1.0  0.0  0.0  0.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0
E  0.0  0.0  0.0  0.0  1.0

In [82]:
df1.drop('E', axis=0, inplace=True)
df1

     V    W    X    Y    Z
A  1.0  0.0  0.0  0.0  0.0
B  0.0  1.0  0.0  0.0  0.0
C  0.0  0.0  1.0  0.0  0.0
D  0.0  0.0  0.0  1.0  0.0

** Removing Columns**

In [83]:
df.drop('new',axis=1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [91]:
# Not inplace unless specified!
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [92]:
df.drop('new',axis=1,inplace=True)

KeyError: "['new'] not found in axis"

In [86]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df1.drop('sum', axis=1)

KeyError: "['sum'] not found in axis"

Can also drop rows this way:

In [87]:
df.drop('E',axis=0)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

** Selecting Rows**

In [93]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

Or select based off of position instead of label

In [94]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

** Selecting subset of rows and columns **

In [200]:
df.loc['B','Y']

-0.84807698340363147

In [105]:
df1
df1.loc[['A','C'],['Y','Z']]

     Y    Z
A  0.0  0.0
C  0.0  0.0

In [201]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [106]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [108]:
df1>0

       V      W      X      Y      Z   sum
A   True  False  False  False  False  True
B  False   True  False  False  False  True
C  False  False   True  False  False  True
D  False  False  False   True  False  True

In [107]:
df>0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [117]:
df1[df1['W']==0]['sum']

A    1.0
C    1.0
D    1.0
Name: sum, dtype: float64

In [204]:
df[df>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [205]:
df[df['W']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [206]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [207]:
df[df['W']>0][['Y','X']]

          Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

For two conditions you can use | and & with parenthesis:

In [208]:
df[(df['W']>0) & (df['Y'] > 1)]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [118]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [119]:
# Reset to default 0,1...n index
df.reset_index()

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [120]:
newind = 'CA NY WY OR CO'.split()

In [135]:
df1['State'] = 'CA NY WY OR'.split()
df1.set_index('State', inplace=True)
df1.reset_index(inplace=True)
df1

  State    V    W    X    Y    Z  sum
0    CA  1.0  0.0  0.0  0.0  0.0  1.0
1    NY  0.0  1.0  0.0  0.0  0.0  1.0
2    WY  0.0  0.0  1.0  0.0  0.0  1.0
3    OR  0.0  0.0  0.0  1.0  0.0  1.0

In [121]:
df['States'] = newind

In [122]:
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [214]:
df.set_index('States')

               W         X         Y         Z
States
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [215]:
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [216]:
df.set_index('States',inplace=True)

In [218]:
df

               W         X         Y         Z
States
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [137]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [138]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [139]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [140]:
df.loc['G1']

          A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [141]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [142]:
df.index.names

FrozenList([None, None])

In [143]:
df.index.names = ['Group','Num']

In [144]:
df

                  A         B
Group Num
G1    1    0.302665  1.693723
      2   -1.706086 -1.159119
      3   -0.134841  0.390528
G2    1    0.166905  0.184502
      2    0.807706  0.072960
      3    0.638787  0.329646

In [145]:
df.xs('G1')

            A         B
Num
1    0.302665  1.693723
2   -1.706086 -1.159119
3   -0.134841  0.390528

In [153]:
df.xs('G1')

            A         B
Num
1    0.302665  1.693723
2   -1.706086 -1.159119
3   -0.134841  0.390528

In [152]:
df.xs(1,level='Num')

              A         B
Group
G1     0.302665  1.693723
G2     0.166905  0.184502

# Great Job!